Repository LSSTDESC/CCL, pull requests merged in 2018-07, with the labels that each got.

#392 Fix neutrino parameter declaration in ccl_sample_angpow.cc; fixes #388
  examples/ccl_sample_angpow.cc
Labels: BUG, Difficulty: Easy

#403 3x2 notebook example
  examples/3x2demo.ipynb
Labels: Python

#321 Readthedocs development
  .gitignore
  pyccl/__init__.py
  pyccl/background.py
  pyccl/cls.py
  pyccl/constants.py
  pyccl/core.py
  pyccl/correlation.py
  pyccl/lsst_specs.py
  pyccl/massfunction.py
  pyccl/neutrinos.py
  pyccl/power.py
  pyccl/pyutils.py
  readthedocs/Makefile
  readthedocs/api/modules.rst
  readthedocs/api/pyccl.background.rst
  readthedocs/api/pyccl.cls.rst
  readthedocs/api/pyccl.constants.rst
  readthedocs/api/pyccl.core.rst
  readthedocs/api/pyccl.correlation.rst
  readthedocs/api/pyccl.lsst_specs.rst
  readthedocs/api/pyccl.massfunction.rst
  readthedocs/api/pyccl.neutrinos.rst
  readthedocs/api/pyccl.power.rst
  readthedocs/api/pyccl.pyutils.rst
  readthedocs/api/pyccl.rst
  readthedocs/apidoc.sh
  readthedocs/conf.py
  readthedocs/index.rst
  readthedocs/source/citation.rst
  readthedocs/source/doxygen_files.rst
  readthedocs/source/installation.rst
  readthedocs/source/installation_for_developers.rst
  readthedocs/source/navigating_the_code.rst.in_development
  readthedocs/source/reporting_bugs.rst
Labels: Documentation
