Repository LSSTDESC/CCL, pull requests merged in 2018-04, with the labels that each got.

#340 Add simple unit tests for all power spectrum methods
  .travis.yml
  README.md
  aclocal.m4
  configure
  pyccl/ccl_wrap.c
  pyccl/ccllib.py
  pyccl/core.py
  src/ccl_core.c
  tests/ccl_test_core.py
  tests/ccl_test_power.py
  tests/ccl_test_pyccl_interface.py
  tests/run_tests.py
Labels: Enhancement, Testing

#306 3dcorrelation
  Makefile.am
  Makefile.in
  doc/0000-ccl_note/0000-ccl_note.pdf
  doc/0000-ccl_note/analytic_xi.pdf
  doc/0000-ccl_note/authors.csv
  doc/0000-ccl_note/authors.tex
  doc/0000-ccl_note/benchmark_xi_abs.pdf
  doc/0000-ccl_note/benchmark_xi_rel.pdf
  doc/0000-ccl_note/contributions.tex
  doc/0000-ccl_note/main.bib
  doc/0000-ccl_note/main.pdf
  doc/0000-ccl_note/main.tex
  include/ccl_correlation.h
  include/ccl_params.h
  include/ccl_params.ini
  pyccl/__init__.py
  pyccl/ccl_correlation.i
  pyccl/ccl_wrap.c
  pyccl/ccllib.py
  pyccl/correlation.py
  src/ccl_core.c
  src/ccl_correlation.c
  tests/Correlation_3d.ipynb
  tests/benchmark/model1_xi.txt
  tests/benchmark/model2_xi.txt
  tests/benchmark/model3_xi.txt
  tests/ccl_3dcorr_sample.c
  tests/ccl_test_correlation_3d.c
Labels: Enhancement

#367 Improve tests in cls.py
  .travis.yml
  install-gsl.sh
  pyccl/cls.py
  pyccl/core.py
  tests/ccl_test_core.py
  tests/ccl_test_pyccl_interface.py
Labels: Checks

#370 Add ability to print C error messages from Python
  .coveragerc
  CONTRIBUTING.md
  include/ccl_error.h
  pyccl/__init__.py
  pyccl/ccl.i
  pyccl/ccl_wrap.c
  pyccl/ccllib.py
  pyccl/pyutils.py
  src/ccl_error.c
  tests/ccl_test_pyccl_interface.py
Labels: Enhancement

#283 Non limber speedup
  .travis.yml
  Makefile.am
  Makefile.in
  README.md
  aclocal.m4
  angpow_install.py
  cleanup.sh
  config.h.in
  configure
  configure.ac
  doc/0000-ccl_note/0000-ccl_note.pdf
  doc/0000-ccl_note/authors.tex
  doc/0000-ccl_note/main.bib
  doc/0000-ccl_note/main.pdf
  doc/0000-ccl_note/main.tex
  examples/ccl_sample_angpow.c
  examples/ccl_sample_run.c
  include/Makefile.in
  include/ccl.h
  include/ccl_background.h
  include/ccl_cls.h
  include/ccl_error.h
  include/ccl_utils.h
  ltmain.sh
  pyccl/ccl_cls.i
  pyccl/ccl_wrap.c
  pyccl/ccllib.py
  pyccl/cls.py
  pyccl/constants.py
  pyccl/correlation.py
  setup.py
  src/ccl_cls.c
  src/ccl_correlation.c
  src/ccl_power.c
  src/ccl_utils.c
  tests/ccl_test_angpow.c
  tests/ccl_test_cls.c
  tests/ccl_test_cmblens.c
  tests/ccl_test_correlation.c
  tests/ccl_test_nonlimber.c
  tests/ccl_test_pyccl_interface.py
Labels: !!SCIENCE!!, C/C++, Difficulty: Hard, Enhancement
