Repository LSSTDESC/CCL, pull requests merged in 2023-03, with the labels that each got.

#983 `HaloModelCalculator` check cosmo in `get_ingredients`.
  pyccl/halos/halo_model.py
  pyccl/tests/test_halofit_highz.py
Labels: BUG

#968 Hashing
  pyccl/__init__.py
  pyccl/base.py
  pyccl/core.py
  pyccl/halos/halo_model.py
  pyccl/halos/massdef.py
  pyccl/tests/test_hashing.py
Labels: Development

#933 Caching framework.
  pyccl/__init__.py
  pyccl/base.py
  pyccl/core.py
  pyccl/tests/test__caching.py
Labels: Development, Optimization

#980 Doc install
  README.md
  pyccl/correlations.py
  readthedocs/api/pyccl.rst
  readthedocs/source/installation.rst
Labels: Documentation

#934 Refactor pyccl under an abstract CCLObject.
  benchmarks/conftest.py
  benchmarks/data/codes/cl_corr_bm/run_all.py
  benchmarks/data/codes/param_space.py
  pyccl/__init__.py
  pyccl/_repr.py
  pyccl/base.py
  pyccl/bcm.py
  pyccl/core.py
  pyccl/halos/__init__.py
  pyccl/halos/concentration.py
  pyccl/halos/halo_model.py
  pyccl/halos/hbias.py
  pyccl/halos/hmfunc.py
  pyccl/halos/massdef.py
  pyccl/halos/profiles.py
  pyccl/halos/profiles_2pt.py
  pyccl/halos/profiles_cib.py
  pyccl/pk2d.py
  pyccl/tests/conftest.py
  pyccl/tests/test__caching.py
  pyccl/tests/test_background.py
  pyccl/tests/test_cclobject.py
  pyccl/tests/test_cls.py
  pyccl/tests/test_concentration.py
  pyccl/tests/test_cosmology.py
  pyccl/tests/test_halomodel.py
  pyccl/tests/test_haloprofile.py
  pyccl/tests/test_hbias.py
  pyccl/tests/test_hmfunc.py
  pyccl/tests/test_massfunction.py
  pyccl/tests/test_neutrinos.py
  pyccl/tests/test_nonlin_camb_power.py
  pyccl/tests/test_parameters.py
  pyccl/tests/test_profiles.py
  pyccl/tests/test_swig_interface.py
  pyccl/tests/test_tkkssc.py
  pyccl/tests/test_tracers.py
  pyccl/tests/test_yaml.py
  pyccl/tk3d.py
  pyccl/tracers.py
Labels: Enhancement, API, Python, Development

#891 Optimize HM autocorrelation power spectra
  pyccl/halos/halo_model.py
  pyccl/halos/profiles.py
  pyccl/halos/profiles_2pt.py
  pyccl/halos/profiles_cib.py
  pyccl/tests/test_cclobject.py
  pyccl/tests/test_pkhm.py
  pyccl/tests/test_profiles.py
  pyccl/tests/test_tkk1h.py
  pyccl/tests/test_tkkssc.py
Labels: Optimization
